### ISSUE TITLE
Cap on pop

### ISSUE THREAD

**Issue by berka1337** [ShawnDriscoll/Traveller-RPG-SectorGen#1]
Great program. This could be useful.

You may need to add a cap on pop.
I get results like this:
C200DBD-9
C967DFH-3

What TL modifier is used for starport X?
I get:
X7B6778-9

Cheers
/P-O

**Comment by ShawnDriscoll** [comment]
Looks like the DMs for Starport got cut out.
Will take a look at planet populations.
Thanks.

**Comment by ShawnDriscoll** [comment]
Looks like an eccentric population rule was in there from Traveller 5.10 (to add some flavor). Will comment it out for the time being.

**Comment by ShawnDriscoll** [comment]
Now that I think about it. I'm just gonna remove as much of the Traveller 5.10 code as I can, since most of it doesn't make any sense for Common Traveller.
